dependencies {
    // compileOnly important!!! We do not want to put the api into the zip file since the main program has it already!
    compileOnly project(':api')

    compileOnly group: 'com.fasterxml.jackson.core', name: 'jackson-databind', version: '2.18.6'
    compileOnly group: 'com.fasterxml.jackson.core', name: 'jackson-core', version: '2.18.6'

    implementation("org.mongodb:mongo-java-driver:3.12.10") {
        exclude group: "org.slf4j"
    }
}
